services:
  gateway:
    build: .
    container_name: szx-gateway
    restart: unless-stopped
    ports:
      - "1005:8080"
      - "1006:8081"
    env_file:
      - .env
    volumes:
      - ./data:/data
