package store

import (
	"database/sql"
	"fmt"
	"time"
)

func (s *Store) migratePostgres() error {
	queries := []string{
		`CREATE TABLE IF NOT EXISTS "keys" (key_hash TEXT PRIMARY KEY, masked_key TEXT NOT NULL, status TEXT NOT NULL, limit_remaining BIGINT NOT NULL DEFAULT 0, usage_today BIGINT NOT NULL DEFAULT 0, usage_day VARCHAR(10) NOT NULL DEFAULT '', max_limit BIGINT NOT NULL DEFAULT 0, is_free_tier SMALLINT NOT NULL DEFAULT 1, rate_limit_req INTEGER NOT NULL DEFAULT 20, rate_limit_interval VARCHAR(32) NOT NULL DEFAULT '1m', cooldown_until TIMESTAMPTZ NOT NULL, last_checked_at TIMESTAMPTZ NOT NULL, last_used_at TIMESTAMPTZ NOT NULL, raw_key TEXT NOT NULL, provider VARCHAR(32) NOT NULL DEFAULT 'openrouter')`,
		`CREATE INDEX IF NOT EXISTS idx_keys_provider ON "keys" (provider)`,
		`CREATE TABLE IF NOT EXISTS requests (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, timestamp TIMESTAMPTZ NOT NULL, key_hash TEXT NOT NULL, model TEXT NOT NULL, status_code INTEGER NOT NULL, prompt_tokens BIGINT NOT NULL DEFAULT 0, completion_tokens BIGINT NOT NULL DEFAULT 0, latency_ms BIGINT NOT NULL DEFAULT 0, error_msg TEXT, ttft_ms BIGINT NOT NULL DEFAULT 0, is_stream SMALLINT NOT NULL DEFAULT 0, provider VARCHAR(32) NOT NULL DEFAULT 'openrouter')`,
		`CREATE INDEX IF NOT EXISTS idx_requests_timestamp ON requests (timestamp)`,
		`CREATE INDEX IF NOT EXISTS idx_requests_key_hash ON requests (key_hash)`,
		`CREATE INDEX IF NOT EXISTS idx_requests_provider ON requests (provider)`,
		`CREATE TABLE IF NOT EXISTS rate_limits_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, timestamp TIMESTAMPTZ NOT NULL, key_hash TEXT NOT NULL, source VARCHAR(32) NOT NULL, limit_total BIGINT, limit_remaining BIGINT, "usage" BIGINT, rate_limit_req BIGINT, rate_limit_interval VARCHAR(32), reset_raw TEXT)`,
		`CREATE INDEX IF NOT EXISTS idx_rl_timestamp ON rate_limits_log (timestamp)`,
		`CREATE INDEX IF NOT EXISTS idx_rl_key_hash ON rate_limits_log (key_hash)`,
		`CREATE TABLE IF NOT EXISTS models_cache (id TEXT PRIMARY KEY, name TEXT NOT NULL, "rank" INTEGER NOT NULL, context_length BIGINT NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
		`CREATE TABLE IF NOT EXISTS free_models_cache (id TEXT PRIMARY KEY, name TEXT NOT NULL, context_length BIGINT NOT NULL, max_output BIGINT NOT NULL DEFAULT 0, type VARCHAR(128) NOT NULL DEFAULT '', features TEXT NOT NULL, modalities TEXT NOT NULL, input_price DOUBLE PRECISION NOT NULL DEFAULT 0, output_price DOUBLE PRECISION NOT NULL DEFAULT 0, description TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
		`CREATE TABLE IF NOT EXISTS aihubmix_free_models_cache (id TEXT PRIMARY KEY, name TEXT NOT NULL, context_length BIGINT NOT NULL DEFAULT 0, max_output BIGINT NOT NULL DEFAULT 0, type VARCHAR(128) NOT NULL DEFAULT '', features TEXT NOT NULL, modalities TEXT NOT NULL, input_price DOUBLE PRECISION NOT NULL DEFAULT 0, output_price DOUBLE PRECISION NOT NULL DEFAULT 0, description TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
		`CREATE TABLE IF NOT EXISTS google_free_models_cache (id TEXT PRIMARY KEY, name TEXT NOT NULL, context_length BIGINT NOT NULL DEFAULT 0, max_output BIGINT NOT NULL DEFAULT 0, type VARCHAR(128) NOT NULL DEFAULT '', features TEXT NOT NULL, modalities TEXT NOT NULL, input_price DOUBLE PRECISION NOT NULL DEFAULT 0, output_price DOUBLE PRECISION NOT NULL DEFAULT 0, description TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL)`,
		`CREATE TABLE IF NOT EXISTS model_usage (provider VARCHAR(32) NOT NULL, key_hash TEXT NOT NULL, model TEXT NOT NULL, day VARCHAR(10) NOT NULL, requests BIGINT NOT NULL DEFAULT 0, tokens BIGINT NOT NULL DEFAULT 0, exhausted SMALLINT NOT NULL DEFAULT 0, latency_sum_ms BIGINT NOT NULL DEFAULT 0, errors BIGINT NOT NULL DEFAULT 0, freeze_count INTEGER NOT NULL DEFAULT 0, frozen_until VARCHAR(64) NOT NULL DEFAULT '', updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY (provider, key_hash, model, day))`,
		`CREATE INDEX IF NOT EXISTS idx_model_usage_day ON model_usage (provider, day, model)`,
		`CREATE TABLE IF NOT EXISTS proxies (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, raw TEXT NOT NULL, scheme VARCHAR(32) NOT NULL, host VARCHAR(255) NOT NULL, port VARCHAR(16) NOT NULL, username VARCHAR(128) NOT NULL DEFAULT '', password VARCHAR(128) NOT NULL DEFAULT '', status VARCHAR(32) NOT NULL DEFAULT 'unchecked', last_checked_at TIMESTAMPTZ NOT NULL, last_error TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, UNIQUE (scheme, host, port, username, password))`,
		`CREATE INDEX IF NOT EXISTS idx_proxies_status ON proxies (status)`,
		`CREATE TABLE IF NOT EXISTS proxy_settings (provider VARCHAR(32) PRIMARY KEY, use_for_checker SMALLINT NOT NULL DEFAULT 0, use_for_requests SMALLINT NOT NULL DEFAULT 0, mode VARCHAR(32) NOT NULL DEFAULT 'after_429')`,
		`CREATE TABLE IF NOT EXISTS proxy_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, timestamp TIMESTAMPTZ NOT NULL, proxy_id BIGINT NOT NULL, provider VARCHAR(32) NOT NULL, use_case VARCHAR(64) NOT NULL, success SMALLINT NOT NULL, request_bytes BIGINT NOT NULL DEFAULT 0, response_bytes BIGINT NOT NULL DEFAULT 0, latency_ms BIGINT NOT NULL DEFAULT 0, error_msg TEXT NOT NULL)`,
		`CREATE INDEX IF NOT EXISTS idx_proxy_logs_timestamp ON proxy_logs (timestamp)`,
		`CREATE TABLE IF NOT EXISTS model_check_configs (provider VARCHAR(32) NOT NULL, model TEXT NOT NULL, enabled SMALLINT NOT NULL DEFAULT 0, position INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (provider, model))`,
		`CREATE TABLE IF NOT EXISTS model_check_results (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, provider VARCHAR(32) NOT NULL, model TEXT NOT NULL, timestamp TIMESTAMPTZ NOT NULL, success SMALLINT NOT NULL, error TEXT NOT NULL)`,
		`CREATE INDEX IF NOT EXISTS idx_model_check_results_lookup ON model_check_results (provider, model, timestamp)`,
	}
	for _, query := range queries {
		if _, err := s.db.Exec(query); err != nil {
			return fmt.Errorf("postgres migration query failed: %w", err)
		}
	}
	_, err := s.db.Exec(`INSERT INTO proxy_settings (provider) VALUES ('openrouter'), ('aihubmix'), ('google') ON CONFLICT (provider) DO NOTHING`)
	return err
}

func (s *Store) reserveModelUsagePostgres(provider, keyHash, model, day string, now time.Time, limit int64) (bool, error) {
	res, err := s.db.Exec(`
		INSERT INTO model_usage (provider, key_hash, model, day, requests, updated_at)
		VALUES (?, ?, ?, ?, 1, ?)
		ON CONFLICT(provider, key_hash, model, day) DO UPDATE SET requests = model_usage.requests + 1, updated_at = excluded.updated_at
		WHERE model_usage.requests < ? AND model_usage.exhausted = 0
	`, provider, keyHash, model, day, now.UTC(), limit)
	if err != nil {
		return false, err
	}
	changed, err := res.RowsAffected()
	return changed > 0, err
}

func (s *Store) freezeModelPostgres(provider, keyHash, model string, now time.Time) (time.Duration, error) {
	day := UTCDay(now)
	tx, err := s.db.Begin()
	if err != nil {
		return 0, err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(`INSERT INTO model_usage (provider, key_hash, model, day, updated_at) VALUES (?, ?, ?, ?, ?) ON CONFLICT (provider, key_hash, model, day) DO NOTHING`, provider, keyHash, model, day, now.UTC()); err != nil {
		return 0, err
	}
	var freezeCount int
	if err := tx.QueryRow(`SELECT freeze_count FROM model_usage WHERE provider = ? AND key_hash = ? AND model = ? AND day = ? FOR UPDATE`, provider, keyHash, model, day).Scan(&freezeCount); err != nil {
		if err == sql.ErrNoRows {
			return 0, fmt.Errorf("model usage row missing after insert")
		}
		return 0, err
	}
	freezeCount++
	until := now.Add(time.Minute)
	if freezeCount > 1 {
		until = now.Add(24 * time.Hour)
	}
	if _, err := tx.Exec(`UPDATE model_usage SET freeze_count = ?, frozen_until = ?, updated_at = ? WHERE provider = ? AND key_hash = ? AND model = ? AND day = ?`, freezeCount, until.UTC().Format(time.RFC3339), now.UTC(), provider, keyHash, model, day); err != nil {
		return 0, err
	}
	if err := tx.Commit(); err != nil {
		return 0, err
	}
	return until.Sub(now), nil
}
